import { StyleSheet, Text, View } from 'react-native';
import type { VerifiedCourseV1 } from '../../engine';
import { AnimatedPressable as Pressable } from '../AnimatedPressable';
import { C } from '../theme';
import { CourseV1Journey } from './CourseV1Journey';
import { CourseV1PlacePreview } from './CourseV1PlacePreview';
import type { CourseV1DisplayPlace } from './courseV1PlacePreviewModel';
import { startMinuteForRecommendation } from './recommendationSessionTime';
export type ConditionalManualState = Readonly<{ loading: boolean; course?: VerifiedCourseV1; error?: string }>;
export function ConditionalVisitSection({ places: conditionalPlaces, nextCursor, displayPlace, onOpenKakao, onMore, manualStates, onConfirm, session, discoveryContext }: { places: readonly { id: string; title: string }[]; nextCursor: number | null; displayPlace: (id: string) => CourseV1DisplayPlace; onOpenKakao: (place: CourseV1DisplayPlace) => void; onMore: () => void; manualStates: Readonly<Record<string, ConditionalManualState>>; onConfirm: (placeId: string) => void; session: { nowIso: string }; discoveryContext: (id: string) => string | null }) {
  if (!conditionalPlaces.length) return null;
  return <View style={s.exploration}><Text style={s.sectionTitle}>운영시간 확인 후 들러볼 곳</Text>{conditionalPlaces.map((place) => { const display = displayPlace(place.id); const manual = manualStates[place.id]; const manualCourse = manual?.course; return <View key={place.id} style={s.card}><Text style={s.courseName}>{place.title}</Text><Text style={s.copy}>운영시간을 카카오맵에서 확인해 주세요</Text><Pressable style={s.secondary} onPress={() => void onOpenKakao(display)}><Text style={s.secondaryText}>카카오맵에서 확인</Text></Pressable><Pressable testID={`conditional-manual-${place.id}`} disabled={manual?.loading} style={s.secondary} onPress={() => void onConfirm(place.id)}><Text style={s.secondaryText}>{manual?.loading ? '실제 경로를 확인하고 있어요' : '확인했어요, 이 장소로 코스 계산'}</Text></Pressable>{manual?.error ? <Text accessibilityRole="alert" style={s.error}>{manual.error}</Text> : null}{manualCourse ? <View style={s.manualResult}><Text style={s.manualLabel}>운영시간 확인 필요(사용자 확인)</Text><CourseV1Journey course={manualCourse} startMin={startMinuteForRecommendation(session.nowIso)} /><View style={s.placeList}>{manualCourse.placeIds.map((id) => <CourseV1PlacePreview key={id} place={displayPlace(id)} context={discoveryContext(id)} onOpenKakao={onOpenKakao} />)}</View></View> : null}</View>; })}{nextCursor !== null ? <Pressable testID="conditional-visit-more" style={s.secondary} onPress={onMore}><Text style={s.secondaryText}>더 보기</Text></Pressable> : null}</View>;
}

const s = StyleSheet.create({ copy: { color: C.muted, fontSize: 13, lineHeight: 20, marginTop: 5 }, card: { padding: 17, gap: 13, borderRadius: 16, borderWidth: 1, borderColor: C.line, backgroundColor: C.panel }, courseName: { color: C.txt, fontSize: 22, lineHeight: 30, fontWeight: '800' }, placeList: { paddingTop: 3, gap: 5 }, manualResult: { gap: 10, borderTopWidth: 1, borderTopColor: C.line, paddingTop: 12 }, manualLabel: { color: '#ffd08a', fontSize: 14, fontWeight: '800' }, error: { color: C.red, fontSize: 13, lineHeight: 19 }, secondary: { minHeight: 52, justifyContent: 'center', alignItems: 'center', borderRadius: 12, borderWidth: 1, borderColor: C.line, backgroundColor: C.panel2 }, secondaryText: { color: C.txt, fontSize: 16, fontWeight: '800' }, exploration: { gap: 10, paddingTop: 10, paddingBottom: 20 }, sectionTitle: { color: C.txt, fontSize: 18, fontWeight: '800' } });

