import { Image, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable as Pressable } from '../AnimatedPressable';
import type { ExplorationPlace } from '../../engine';
import { C } from '../theme';
import { buildKakaoPlaceUrl, getPlacePreviewKind, type CourseV1DisplayPlace } from './courseV1PlacePreviewModel';

export function ExplorationPlaceCard({ place, displayPlace, context, loading, error, onSelect, onOpenKakao }: { place: ExplorationPlace; displayPlace: CourseV1DisplayPlace; context: string | null; loading: boolean; error: string | null; onSelect: () => void; onOpenKakao: () => void }) {
  const preview = getPlacePreviewKind(displayPlace, false);
  const kakaoUrl = buildKakaoPlaceUrl(displayPlace);
  return <View style={s.card}><View style={s.media}>{preview.kind === 'image' ? <Image accessibilityLabel={`${place.title} ${preview.sourceLabel}`} source={{ uri: displayPlace.imageUrl! }} style={s.image} /> : <View accessibilityLabel={`${place.title} 사진 없음`} style={s.placeholder}><Text style={s.placeholderText}>{context ?? '장소 미리보기'}</Text></View>}</View><View style={s.content}><Text style={s.title}>{place.title}</Text>{context ? <Text style={s.context}>{context}</Text> : null}{place.eligibility === 'area_access' ? <Text style={s.area}>가볍게 둘러보기 · 약 20분</Text> : null}{error ? <Text accessibilityRole="alert" style={s.error}>{error}</Text> : null}<View style={s.actions}><Pressable accessibilityLabel={`${place.title} 선택해 경로 확인`} disabled={loading} style={[s.action, loading && s.actionOff]} onPress={onSelect}><Text style={s.actionText}>{loading ? '경로 확인 중' : '선택해 확인'}</Text></Pressable>{kakaoUrl ? <Pressable accessibilityLabel={`${place.title} 카카오맵에서 확인`} style={s.link} onPress={onOpenKakao}><Text style={s.linkText}>카카오맵에서 확인</Text></Pressable> : null}</View></View></View>;
}

const s = StyleSheet.create({ card: { flexDirection: 'row', gap: 11, padding: 13, borderRadius: 14, borderWidth: 1, borderColor: C.line, backgroundColor: C.panel }, media: { width: 76, height: 76, borderRadius: 10, overflow: 'hidden', backgroundColor: C.panel2 }, image: { width: '100%', height: '100%' }, placeholder: { flex: 1, padding: 8, justifyContent: 'center', alignItems: 'center', backgroundColor: '#26384a' }, placeholderText: { color: '#b9d8ff', fontSize: 11, lineHeight: 15, fontWeight: '700', textAlign: 'center' }, content: { flex: 1, gap: 4 }, title: { color: C.txt, fontSize: 16, fontWeight: '800' }, context: { color: '#b9d8ff', fontSize: 13, fontWeight: '700' }, area: { color: '#ffd08a', fontSize: 13, fontWeight: '800' }, error: { color: C.red, fontSize: 12, lineHeight: 18 }, actions: { flexDirection: 'row', alignItems: 'center', gap: 14 }, action: { minHeight: 32, justifyContent: 'center' }, actionOff: { opacity: 0.55 }, actionText: { color: '#75b1ff', fontSize: 13, fontWeight: '800' }, link: { minHeight: 32, justifyContent: 'center' }, linkText: { color: '#b9d8ff', fontSize: 13, fontWeight: '800' } });
