#!/usr/bin/env node
// `실경로_수집계획.json`의 명시 거점·후보만 실제 TMAP 도보 경로로 조회한다.
import fs from 'node:fs';
const PLAN='data/processed/review/실경로_수집계획.json', PROFILE='data/processed/review/부산_장소_근거프로필_재분류.json', OUTPUT='data/processed/review/장소쌍_실경로_계획스냅샷.json';
const key=process.env.EXPO_PUBLIC_TMAP_APP_KEY||process.env.TMAP_APP_KEY;if(!key)throw new Error('TMAP key required');
const plan=JSON.parse(fs.readFileSync(PLAN,'utf8')).data,places=new Map(JSON.parse(fs.readFileSync(PROFILE,'utf8')).data.map(p=>[p.id,p]));
const slug=s=>s.replaceAll('구','').replaceAll('군','');
const point=(id,reason)=>{const p=places.get(id);if(!p)throw new Error(`missing ${id}`);return{id:p.id,title:p.title,lat:p.lat,lon:p.lon,reason};};
const base=[];for(const row of plan){const origin=point(row.origin.placeId,row.origin.reason),destination=point(row.destination.placeId,row.destination.reason),candidates=row.candidatePlaceIds.map(id=>point(id,'구조화 운영시간 대표 후보'));
  if(candidates.length){base.push({id:`PLAN-${slug(row.borough)}-ORIGIN-${candidates[0].id}`,area:row.borough,from:origin,to:candidates[0]});for(let i=0;i<candidates.length-1;i++)base.push({id:`PLAN-${slug(row.borough)}-${candidates[i].id}-${candidates[i+1].id}`,area:row.borough,from:candidates[i],to:candidates[i+1]});base.push({id:`PLAN-${slug(row.borough)}-${candidates.at(-1).id}-RETURN`,area:row.borough,from:candidates.at(-1),to:origin});for(const candidate of candidates)base.push({id:`PLAN-${slug(row.borough)}-${candidate.id}-DESTINATION`,area:row.borough,from:candidate,to:destination});}}
async function query(pair){const res=await fetch('https://apis.openapi.sk.com/tmap/routes/pedestrian?version=1&format=json',{method:'POST',headers:{appKey:key,'Content-Type':'application/json'},body:JSON.stringify({startX:pair.from.lon,startY:pair.from.lat,endX:pair.to.lon,endY:pair.to.lat,reqCoordType:'WGS84GEO',resCoordType:'WGS84GEO',startName:'출발',endName:'도착'})}),base={...pair,fromId:pair.from.id,toId:pair.to.id,retrievedAt:new Date().toISOString()};if(!res.ok)return{...base,status:'failed',httpStatus:res.status};const body=await res.text();let json;try{json=JSON.parse(body);}catch{return{...base,status:'invalid_response',httpStatus:res.status,responseSummary:{bodyLength:body.length,parseError:'non_json_or_empty'}};}const prop=json?.features?.[0]?.properties??{};return{...base,status:Number.isFinite(prop.totalTime)?'ok':'invalid_response',mode:'walk',totalMoveMin:Math.round(prop.totalTime/60),totalDistanceM:prop.totalDistance??null,provider:'TMAP pedestrian routes',responseSummary:{featureCount:json?.features?.length??0,totalTimeSec:prop.totalTime??null,totalDistance:prop.totalDistance??null}};}
const previous=fs.existsSync(OUTPUT)?JSON.parse(fs.readFileSync(OUTPUT,'utf8')).data:[],cached=new Map(previous.filter(p=>p.status==='ok').map(p=>[`${p.fromId}:${p.toId}`,p]));const data=[];for(const pair of base){const old=cached.get(`${pair.from.id}:${pair.to.id}`);data.push(old?{...old,id:pair.id,area:pair.area,from:pair.from,to:pair.to,fromId:pair.from.id,toId:pair.to.id}:await query(pair));if(!old)await new Promise(resolve=>setTimeout(resolve,120));}
const summary={planned:base.length,ok:data.filter(p=>p.status==='ok').length,failed:data.filter(p=>p.status!=='ok').length};fs.writeFileSync(OUTPUT,`${JSON.stringify({meta:{generatedAt:new Date().toISOString(),purpose:'16개 생활권 수집계획의 실제 TMAP 도보 구간 스냅샷',sourcePlan:PLAN,calls:data.length},summary,data},null,2)}\n`);console.log(`계획 실경로 스냅샷: ${summary.ok}/${summary.planned}`);
