#!/usr/bin/env node
// 실제 경로가 없는 매트릭스를 route_verified_measurement로 오인하지 않도록 전체 고정 시나리오의 커버리지를 감사한다.
import fs from 'node:fs';
const SUPPLY='data/processed/review/코스공급량_고정시나리오.json', VERIFIED='data/processed/review/코스공급량_실경로검증_시나리오.json', MEASURED='data/processed/review/코스공급량_부산500m_실경로측정.json', OUTPUT='data/processed/review/코스공급량_실경로검증_커버리지.json', REPORT='docs/02_data/코스공급량_실경로검증_커버리지.md';
const supply=JSON.parse(fs.readFileSync(SUPPLY,'utf8')),verified=JSON.parse(fs.readFileSync(VERIFIED,'utf8')),measured=fs.existsSync(MEASURED)?JSON.parse(fs.readFileSync(MEASURED,'utf8')):{scenarios:[]};
const key=x=>JSON.stringify({borough:x.borough,dayType:x.dayType,now:x.now,budgetMin:x.budgetMin,arrivalType:x.arrivalType});
const byMatrix=new Map();
for(const scenario of verified.scenarios){if(scenario.measurementGrade!=='route_verified_measurement')continue;const k=key(scenario.coverageMatrixKey);const rows=byMatrix.get(k)??[];rows.push(scenario);byMatrix.set(k,rows);}
for(const scenario of measured.scenarios){if(scenario.measurementGrade!=='route_verified_measurement'||!scenario.fullCandidateScope)continue;const k=key(scenario.coverageMatrixKey);const rows=byMatrix.get(k)??[];rows.push(scenario);byMatrix.set(k,rows);}
const data=supply.scenarios.map(s=>{const rows=byMatrix.get(key(s))??[],sizes=new Set(rows.flatMap(r=>r.fullCandidateScope?Object.keys(r.courseSizeComparison).map(Number):[(r.places??[r.place]).length])),allSegmentsReal=rows.every(r=>r.fullCandidateScope?r.actualRouteEvaluatedCourseCount===r.relationshipFilteredCourseCount&&!r.zeroReasonBreakdown.missing_actual_route:r.segments.every(p=>p.status==='ok'&&p.provider==='TMAP pedestrian routes'));
  const complete=allSegmentsReal&&[1,2,3].every(size=>sizes.has(size));
  return {scenarioId:s.scenarioId,borough:s.borough,dayType:s.dayType,now:s.now,budgetMin:s.budgetMin,arrivalType:s.arrivalType,measurementGrade:complete?'route_verified_measurement':'heuristic_diagnostic',routeVerifiedCourseSizes:[...sizes].sort(),routeVerifiedScenarioIds:rows.map(r=>r.scenarioId),status:complete?'complete_real_route_1_to_3':'missing_full_real_route_1_to_3',missingReason:complete?null:'no full policy-range 1·2·3-place actual-route set with structured availability for this matrix'};
});
const complete=data.filter(r=>r.measurementGrade==='route_verified_measurement'), diagnosticSlices=measured.scenarios.filter(s=>s.measurementGrade==='route_verified_diagnostic_slice'), summary={matrixTotal:data.length,routeVerifiedMatrixCount:complete.length,heuristicDiagnosticMatrixCount:data.length-complete.length,routeVerifiedZeroResultRate:null,diagnosticSliceScenarioCount:diagnosticSlices.length,diagnosticSliceZeroResultRate:diagnosticSlices.length?diagnosticSlices.filter(s=>!s.representativeCourseCount).length/diagnosticSlices.length:null,heuristicDiagnosticZeroResultRate:supply.summary.heuristicDiagnostic.zeroResultRate,conclusion:'현행 제품의 실제 경로 주변 생활권 후보 범위를 전부 평가한 route_verified_measurement는 아직 없다. 부산 500m 실제 경로 결과는 route_verified_diagnostic_slice로 보존하며, 그 0개율은 공급량 결론이나 데이터 보강 우선순위에 사용하지 않는다.'};
fs.writeFileSync(OUTPUT,`${JSON.stringify({meta:{generatedAt:'2026-08-24',sources:[SUPPLY,VERIFIED,MEASURED]},summary,data},null,2)}\n`);
const rows=data.map(r=>`| ${r.borough} | ${r.now} | ${r.budgetMin} | ${r.arrivalType} | ${r.measurementGrade} | ${r.routeVerifiedCourseSizes.join(',')||'-'} | ${r.status} |`).join('\n');
fs.writeFileSync(REPORT,['# 실경로 공급량 매트릭스 커버리지','',`- 전체 매트릭스: ${summary.matrixTotal}개`, `- 현행 제품 후보 범위를 충족한 route_verified_measurement: ${summary.routeVerifiedMatrixCount}개`, `- heuristic_diagnostic(현행 정책 범위의 실경로 전 구간 1·2·3곳 미충족): ${summary.heuristicDiagnosticMatrixCount}개`, `- 별도 500m 실제 경로 진단 slice: ${summary.diagnosticSliceScenarioCount}개(공급량 결론 미사용)`, '- 전체 부산의 실경로 공급량·0개율은 **미산출**이다. 500m slice와 근사 진단의 0개율을 데이터 보강 우선순위로 쓰지 않는다.', '', '| 생활권 | 시각 | 예산 | 도착 | 등급 | 실제 비교 장소 수 | 상태 |','| --- | --- | ---: | --- | --- | --- | --- |',rows,'',`상세 JSON: \`${OUTPUT}\``].join('\n')+'\n');
console.log(`실경로 커버리지: ${summary.routeVerifiedMatrixCount}/${summary.matrixTotal}`);
