#!/usr/bin/env node
// 500m 진단 slice 안의 모든 구조화 대표 후보에 대해 1~3곳 순열에 필요한 실제 TMAP 도보 구간을 수집한다.
import fs from 'node:fs';
const PROFILE='data/processed/review/부산_장소_근거프로필_재분류.json', AVAILABILITY='data/processed/review/부산_장소_구조화_운영시간.json', OUTPUT='data/processed/review/남포_500m_실경로_장소쌍_스냅샷.json';
const apiKey=process.env.EXPO_PUBLIC_TMAP_APP_KEY||process.env.TMAP_APP_KEY;if(!apiKey)throw new Error('TMAP key required');
const places=JSON.parse(fs.readFileSync(PROFILE,'utf8')).data, availability=new Map(JSON.parse(fs.readFileSync(AVAILABILITY,'utf8')).data.map(a=>[a.placeId,a])),byId=new Map(places.map(p=>[p.id,p]));
const origin=byId.get('poi_13'),destination=byId.get('poi_92'),radiusM=500,rad=x=>x*Math.PI/180,meters=(a,b)=>6371000*2*Math.asin(Math.sqrt(Math.sin(rad(b.lat-a.lat)/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(rad(b.lon-a.lon)/2)**2));
const candidates=places.filter(p=>p.classification.startsWith('representative')&&availability.get(p.id)?.status==='structured'&&p.id!==origin.id&&meters(origin,p)<=radiusM&&!(p.lat===origin.lat&&p.lon===origin.lon)&&!(p.siteGroupId&&p.siteGroupId===origin.siteGroupId));
const fromNodes=[origin,...candidates],toNodes=[origin,...candidates,destination],pairs=[];for(const from of fromNodes)for(const to of toNodes)if(from.id!==to.id)pairs.push({id:`NAMPO-500M-${from.id}-${to.id}`,from:{id:from.id,title:from.title,lat:from.lat,lon:from.lon},to:{id:to.id,title:to.title,lat:to.lat,lon:to.lon}});
async function query(pair){const res=await fetch('https://apis.openapi.sk.com/tmap/routes/pedestrian?version=1&format=json',{method:'POST',headers:{appKey:apiKey,'Content-Type':'application/json'},body:JSON.stringify({startX:pair.from.lon,startY:pair.from.lat,endX:pair.to.lon,endY:pair.to.lat,reqCoordType:'WGS84GEO',resCoordType:'WGS84GEO',startName:'출발',endName:'도착'})}),base={...pair,fromId:pair.from.id,toId:pair.to.id,retrievedAt:new Date().toISOString()};if(!res.ok)return{...base,status:'failed',httpStatus:res.status};const text=await res.text();let json;try{json=JSON.parse(text);}catch{return{...base,status:'invalid_response',httpStatus:res.status,responseSummary:{bodyLength:text.length}};}const prop=json?.features?.[0]?.properties??{};return{...base,status:Number.isFinite(prop.totalTime)?'ok':'invalid_response',mode:'walk',totalMoveMin:Math.round(prop.totalTime/60),totalDistanceM:prop.totalDistance??null,provider:'TMAP pedestrian routes',responseSummary:{featureCount:json?.features?.length??0,totalTimeSec:prop.totalTime??null,totalDistance:prop.totalDistance??null}};}
const data=[];for(const pair of pairs){data.push(await query(pair));await new Promise(r=>setTimeout(r,120));}const summary={candidateCount:candidates.length,pairCount:pairs.length,ok:data.filter(p=>p.status==='ok').length,failed:data.filter(p=>p.status!=='ok').length};fs.writeFileSync(OUTPUT,`${JSON.stringify({meta:{generatedAt:new Date().toISOString(),policy:{area:'중구 남포권',originId:origin.id,destinationId:destination.id,radiusM,candidateScope:'origin 500m 반경의 모든 structured representative, 동일 좌표·same siteGroup 제외; top-N 절단 없음'},candidatePlaceIds:candidates.map(p=>p.id)},summary,data},null,2)}\n`);console.log(`남포 500m 실제 경로: ${summary.ok}/${summary.pairCount}, 후보 ${summary.candidateCount}`);
