#!/usr/bin/env node
// 각 생활권의 명시 거점 500m 진단 slice에 있는 모든 구조화 대표 후보의 실제 TMAP 도보 구간을 수집한다.
import fs from 'node:fs';
const PROFILE='data/processed/review/부산_장소_근거프로필_재분류.json',AVAILABILITY='data/processed/review/부산_장소_구조화_운영시간.json',PLAN='data/processed/review/실경로_수집계획.json',OUTPUT='data/processed/review/부산_500m_실경로_장소쌍_스냅샷.json',RADIUS=500;
const apiKey=process.env.EXPO_PUBLIC_TMAP_APP_KEY||process.env.TMAP_APP_KEY;if(!apiKey)throw new Error('TMAP key required');const places=JSON.parse(fs.readFileSync(PROFILE,'utf8')).data,byId=new Map(places.map(p=>[p.id,p])),availability=new Map(JSON.parse(fs.readFileSync(AVAILABILITY,'utf8')).data.map(a=>[a.placeId,a])),plans=JSON.parse(fs.readFileSync(PLAN,'utf8')).data,rad=x=>x*Math.PI/180,meters=(a,b)=>6371000*2*Math.asin(Math.sqrt(Math.sin(rad(b.lat-a.lat)/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(rad(b.lon-a.lon)/2)**2));
const point=(p,reason)=>({id:p.id,title:p.title,lat:p.lat,lon:p.lon,reason});const scopes=plans.map(plan=>{const origin=byId.get(plan.origin.placeId),destination=byId.get(plan.destination.placeId),candidates=places.filter(p=>p.classification.startsWith('representative')&&availability.get(p.id)?.status==='structured'&&p.id!==origin.id&&meters(origin,p)<=RADIUS&&!(p.lat===origin.lat&&p.lon===origin.lon)&&!(p.siteGroupId&&p.siteGroupId===origin.siteGroupId));return{borough:plan.borough,origin:point(origin,plan.origin.reason),destination:point(destination,plan.destination.reason),candidatePlaceIds:candidates.map(p=>p.id),candidates:candidates.map(p=>point(p,'500m 진단 slice structured representative'))};});
const pairSpecs=[];for(const scope of scopes){const from=[scope.origin,...scope.candidates],to=[scope.origin,...scope.candidates,scope.destination];for(const a of from)for(const b of to)if(a.id!==b.id&&scope.candidates.length)pairSpecs.push({id:`BUSAN-500M-${scope.borough}-${a.id}-${b.id}`,area:scope.borough,from:a,to:b});}
async function query(pair){const res=await fetch('https://apis.openapi.sk.com/tmap/routes/pedestrian?version=1&format=json',{method:'POST',headers:{appKey:apiKey,'Content-Type':'application/json'},body:JSON.stringify({startX:pair.from.lon,startY:pair.from.lat,endX:pair.to.lon,endY:pair.to.lat,reqCoordType:'WGS84GEO',resCoordType:'WGS84GEO',startName:'출발',endName:'도착'})}),base={...pair,fromId:pair.from.id,toId:pair.to.id,retrievedAt:new Date().toISOString()};if(!res.ok)return{...base,status:'failed',httpStatus:res.status};const body=await res.text();let json;try{json=JSON.parse(body)}catch{return{...base,status:'invalid_response',httpStatus:res.status,responseSummary:{bodyLength:body.length}}}const prop=json?.features?.[0]?.properties??{};return{...base,status:Number.isFinite(prop.totalTime)?'ok':'invalid_response',mode:'walk',totalMoveMin:Math.round(prop.totalTime/60),totalDistanceM:prop.totalDistance??null,provider:'TMAP pedestrian routes',responseSummary:{featureCount:json?.features?.length??0,totalTimeSec:prop.totalTime??null,totalDistance:prop.totalDistance??null}};}
const data=[];for(const pair of pairSpecs){data.push(await query(pair));await new Promise(resolve=>setTimeout(resolve,120));}const summary={areaCount:scopes.length,pairCount:data.length,ok:data.filter(p=>p.status==='ok').length,failed:data.filter(p=>p.status!=='ok').length,candidateCounts:Object.fromEntries(scopes.map(s=>[s.borough,s.candidatePlaceIds.length]))};fs.writeFileSync(OUTPUT,`${JSON.stringify({meta:{generatedAt:new Date().toISOString(),policy:{radiusM:RADIUS,candidateScope:'각 명시 출발 거점 500m 반경의 모든 structured representative; 동일 좌표·명시 same siteGroup·내부장소 제외; top-N 없음'}},summary,scopes,data},null,2)}\n`);console.log(`부산 500m 실제 경로: ${summary.ok}/${summary.pairCount}`);
