#!/usr/bin/env node
// 오프라인 휴리스틱 진단 fixture. 실제 TMAP/ODsay 스냅샷이 연결되기 전에는 공급량 결론에 쓰지 않는다.
import fs from 'node:fs';
const PROFILE='data/processed/review/부산_장소_근거프로필_재분류.json',AVAILABILITY='data/processed/review/부산_장소_구조화_운영시간.json',PAIRS='data/processed/review/장소쌍_실경로_스냅샷.json',OUTPUT='data/processed/review/코스공급량_고정시나리오.json',REPORT='docs/02_data/코스공급량_고정시나리오_측정.md';
const BOROUGHS=['중구','서구','동구','영도구','부산진구','동래구','남구','북구','해운대구','사하구','금정구','강서구','연제구','수영구','사상구','기장군'];
const SLOTS=[['weekday_morning','weekday','10:00',600],['weekday_afternoon','weekday','14:00',840],['weekday_evening','weekday','18:00',1080],['weekend_afternoon','weekend','14:00',840]],BUDGETS=[45,60,90,180];
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')), borough=(a='')=>[...BOROUGHS].sort((x,y)=>y.length-x.length).find(x=>a.includes(x))??'권역미확인',rad=x=>x*Math.PI/180;
const dist=(a,b)=>{const x=rad(b.lat-a.lat),y=rad(b.lon-a.lon),h=Math.sin(x/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(y/2)**2;return 6371000*2*Math.asin(Math.sqrt(h));};
const segment=(a,b)=>{const meters=Math.max(1,Math.round(dist(a,b)));return{from:a.id,to:b.id,meters,walkMin:Math.max(2,Math.ceil(meters/72)+1),transitMin:Math.max(5,Math.ceil(meters/280)+4),source:'heuristic_coordinate_speed_diagnostic_not_live_route'};};
function open(p,at,stay,day){const a=availabilityByPlace.get(p.id);return a?.status==='structured'&&a.dayTypes.includes(day)&&a.windows.some(w=>at>=w.startMin&&at+stay<=w.endMin);}
function perm(a,n){if(!n)return[[]];return a.flatMap((x,i)=>perm(a.filter((_,j)=>j!==i),n-1).map(t=>[x,...t]));}
// 같은 장소·동일 siteGroup·내부장소만 hard block한다. 활동 유형 반복은 다양성 순위 신호일 뿐
// 코스 후보를 삭제하는 조건이 아니다.
function allowed(c){const ids=new Set(c.map(p=>p.id)),groups=c.map(p=>p.siteGroupId).filter(Boolean);return ids.size===c.length&&groups.length===new Set(groups).size&&!c.some(p=>p.scope?.type==='내부장소');}
function evalCourse(c,o,d,sc){let clock=sc.minute,cursor=o,travel=0;const segments=[];for(const p of c){const s=segment(cursor,p),m=Math.min(s.walkMin,s.transitMin);segments.push({...s,chosenMin:m});travel+=m;clock+=m;if(!open(p,clock,p.recommendedStayMin,sc.day))return null;clock+=p.recommendedStayMin;cursor=p;}const s=segment(cursor,d),m=Math.min(s.walkMin,s.transitMin);segments.push({...s,chosenMin:m});travel+=m;const stay=c.reduce((n,p)=>n+p.recommendedStayMin,0),total=travel+stay+10;return total<=sc.budget?{placeIds:c.map(p=>p.id),segments,totalTravelMin:travel,totalStayMin:stay,totalMin:total}:null;}
const places=read(PROFILE).data.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)),availabilityByPlace=new Map(read(AVAILABILITY).data.map(a=>[a.placeId,a])),pairSnapshot=fs.existsSync(PAIRS)?read(PAIRS):{summary:{ok:0},data:[]},reps=places.filter(p=>['representative_core','representative_standard'].includes(p.classification)),scenarios=[];
for(const area of BOROUGHS)for(const [slot,day,now,minute] of SLOTS)for(const budget of BUDGETS){const areaRows=reps.filter(p=>borough(p.address)===area),anchors=places.filter(p=>borough(p.address)===area),first=anchors[0],last=anchors.at(-1);if(!first||!last)throw new Error(`${area}: valid coordinate anchor missing`);for(const arrivalType of ['return_to_origin','separate_destination']){const origin={id:`${area}:origin:${first.id}`,lat:first.lat,lon:first.lon,sourcePlaceId:first.id},destination=arrivalType==='return_to_origin'?origin:{id:`${area}:destination:${last.id}`,lat:last.lat,lon:last.lon,sourcePlaceId:last.id};const openCandidates=areaRows.filter(p=>open(p,minute,p.recommendedStayMin,day)).sort((a,b)=>dist(origin,a)-dist(origin,b)),usable=openCandidates.slice(0,5),excluded=openCandidates.slice(5),raw=[1,2,3].flatMap(n=>perm(usable,n)),related=raw.filter(allowed),feasible=related.map(c=>evalCourse(c,origin,destination,{day,minute,budget})).filter(Boolean),best=new Map();for(const c of feasible){const k=c.placeIds.slice().sort().join('|');if(!best.has(k)||best.get(k).totalMin>c.totalMin)best.set(k,c);}const courses=[...best.values()].sort((a,b)=>a.totalMin-b.totalMin||a.placeIds.join('|').localeCompare(b.placeIds.join('|'))),reason=!areaRows.length?'spatial_no_representative':!usable.length?'opening_hours':!related.length?'relationship_duplicate_or_internal':!courses.length?'minimum_stay_or_heuristic_pair_budget':null;scenarios.push({scenarioId:`SUPPLY-${area}-${slot}-${budget}-${arrivalType}`,fixtureKind:'heuristic_diagnostic_coordinate_pair_fixture',measurementGrade:'heuristic_diagnostic',borough:area,dayType:day,now,origin,destination,arrivalType,budgetMin:budget,arrivalBufferMin:10,eligibleCandidateCount:openCandidates.length,localTopN:5,candidatePlaceIds:usable.map(p=>p.id),excludedCandidatePlaceIds:excluded.map(p=>p.id),candidateSelectionWarning:'localTopN은 휴리스틱 진단 비용 제한이다. route_verified_measurement의 공급량·0개율 결론에는 사용하지 않는다.',placeContracts:usable.map(p=>({placeId:p.id,coordinates:{lat:p.lat,lon:p.lon},classification:p.classification,availability:p.availability,siteGroupId:p.siteGroupId??null,activityType:p.shortStayType,shortStay:{min:p.minStayMin,recommended:p.recommendedStayMin,max:p.maxStayMin}})),rawCoursePermutationCount:raw.length,relationshipFilteredCourseCount:related.length,deduplicatedFeasibleCourseCount:courses.length,representativeCourseCount:courses.length?1:0,newRecommendationCount:Math.max(0,courses.length-1),representativeCourse:courses[0]??null,alternativeCourses:courses.slice(1),nextRecommendationState:!courses.length?'no_candidates':courses.length===1?'no_alternative_verified_course':'alternatives_available',zeroCandidateReason:reason});}}
const count=(a,f)=>Object.fromEntries([...a.reduce((m,x)=>{const k=f(x);m.set(k,(m.get(k)??0)+1);return m},new Map()).entries()]);
const payload={meta:{generatedAt:'2026-08-24',source:PROFILE,availabilitySource:AVAILABILITY,measurementGrade:'heuristic_diagnostic',warning:'좌표는 런타임 카탈로그지만 pair 이동시간은 실제 경로 스냅샷이 아닌 직선거리·속도식 진단값이다. route_verified_measurement 또는 데이터 보강 우선순위 근거로 사용 금지.'},summary:{total:scenarios.length,heuristicDiagnostic:{zeroResultRate:scenarios.filter(s=>!s.representativeCourseCount).length/scenarios.length,zeroReasonBreakdown:count(scenarios.filter(s=>s.zeroCandidateReason),s=>s.zeroCandidateReason),representativeCourseCount:scenarios.reduce((n,s)=>n+s.representativeCourseCount,0),newRecommendationCount:scenarios.reduce((n,s)=>n+s.newRecommendationCount,0)},routeVerifiedMeasurement:{total:0,pairTravelSnapshotCount:pairSnapshot.summary.ok??0,conclusion:'실경로 pairTravelFixture는 수집됐지만 전체 부산 매트릭스는 실제 경로를 아직 연결하지 않아 공급량 결론 미산출'}},scenarios};fs.writeFileSync(OUTPUT,`${JSON.stringify(payload,null,2)}\n`);
const sizeDistribution=count(scenarios.flatMap(s=>[s.representativeCourse,...s.alternativeCourses].filter(Boolean)),c=>c.placeIds.length);
const matrix=scenarios.map(s=>`| ${s.borough} | ${s.now} | ${s.budgetMin} | ${s.arrivalType} | ${s.eligibleCandidateCount} | ${s.rawCoursePermutationCount} | ${s.relationshipFilteredCourseCount} | ${s.deduplicatedFeasibleCourseCount} | ${s.representativeCourseCount} | ${s.newRecommendationCount} | ${s.zeroCandidateReason??'-'} |`).join('\n');
fs.writeFileSync(REPORT,['# 코스 공급량 고정 시나리오 측정','',`- 시나리오: ${scenarios.length}개 (16 생활권 × 4 시간대 × 4 예산 × 2 도착 형태)`,'- 결과 등급: **heuristic_diagnostic**. 실제 TMAP/ODsay pairTravelFixture가 없는 구간을 속도식으로 계산한 수치로 추천 공급량·0개율·데이터 보강 우선순위를 결론내리지 않는다.',`- 실제 TMAP 도보 pairTravel 스냅샷: ${pairSnapshot.summary.ok??0}개. 실경로 코스 fixture는 별도 파일에서만 route_verified_measurement로 취급한다.`,'','## 측정 정의','','- rawCoursePermutationCount는 참고값이며 추천량/새 추천 수로 사용하지 않는다.','- localTopN=5의 후보·제외 ID를 함께 기록한다. 이 절단은 휴리스틱 진단에만 허용되며 route_verified_measurement에는 허용되지 않는다.','- 동일 장소·siteGroup·내부장소만 hard block하며 활동 유형 반복은 순위 신호일 뿐 후보 제외 사유가 아니다.','- 이 파일의 deduplicatedFeasibleCourseCount 등은 fixture 구조 검증용 진단값이다.','','## 휴리스틱 진단 합계 (결론 사용 금지)','',`- 대표 코스 0개율: ${(payload.summary.heuristicDiagnostic.zeroResultRate*100).toFixed(1)}%` ,`- 0개 사유: ${JSON.stringify(payload.summary.heuristicDiagnostic.zeroReasonBreakdown)}`,`- 보존된 1·2·3곳 코스 분포: ${JSON.stringify(sizeDistribution)}`,'','## 생활권·시간대·예산·도착 형태별 진단','','| 생활권 | 시각 | 예산 | 도착 | 적격 후보 | 원시 순열 | 관계 통과 | 중복 제거 유효 | 대표 | 새 추천 | 0개 사유 |','| --- | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |',matrix,'','## 엔진·UIUX 인계','','- 엔진: 실제 pairTravelFixture가 연결된 뒤에만 representativeCourse/alternativeCourses의 segments를 경로 검증 입력으로 쓴다.','- UIUX: no_candidates=빈 결과, no_alternative_verified_course=“이 조건에서 다른 검증 코스가 없습니다”, alternatives_available=미확인 대체 코스 가능 상태다.','',`상세 fixture: \`${OUTPUT}\``].join('\n')+'\n');console.log(`코스 공급량 fixture: ${scenarios.length}개 -> ${OUTPUT}`);
