#!/usr/bin/env node
// 남포권 500m 진단 slice의 모든 구조화 대표 후보를 실제 TMAP 구간으로 평가한다.
import fs from 'node:fs';
const PROFILE='data/processed/review/부산_장소_근거프로필_재분류.json', AVAILABILITY='data/processed/review/부산_장소_구조화_운영시간.json', PAIRS='data/processed/review/남포_500m_실경로_장소쌍_스냅샷.json', OUTPUT='data/processed/review/코스공급량_남포500m_실경로측정.json', REPORT='docs/02_data/코스공급량_남포500m_실경로측정.md';
const places=JSON.parse(fs.readFileSync(PROFILE,'utf8')).data,byId=new Map(places.map(p=>[p.id,p])),availability=new Map(JSON.parse(fs.readFileSync(AVAILABILITY,'utf8')).data.map(a=>[a.placeId,a])),pairFile=JSON.parse(fs.readFileSync(PAIRS,'utf8')),pairs=new Map(pairFile.data.filter(p=>p.status==='ok').map(p=>[`${p.fromId}:${p.toId}`,p]));
const origin=byId.get('poi_13'),destination=byId.get('poi_92'),candidateIds=pairFile.meta.candidatePlaceIds,candidates=candidateIds.map(id=>byId.get(id));
if(pairFile.summary.failed)throw new Error('actual pair snapshot contains failures');
const slots=[['weekday_morning','weekday','10:00',600],['weekday_afternoon','weekday','14:00',840],['weekday_evening','weekday','18:00',1080],['weekend_afternoon','weekend','14:00',840]],budgets=[45,60,90,180],buffer=10,perm=(items,n)=>n?items.flatMap((item,index)=>perm(items.filter((_,i)=>i!==index),n-1).map(t=>[item,...t])):[[]];
const available=(p,day,start,end)=>{const a=availability.get(p.id);return a?.status==='structured'&&a.dayTypes.includes(day)&&a.windows.some(w=>start>=w.startMin&&end<=w.endMin);};
const allowed=course=>{const ids=new Set(course.map(p=>p.id)),groups=course.map(p=>p.siteGroupId).filter(Boolean);return ids.size===course.length&&groups.length===new Set(groups).size&&!course.some(p=>p.scope?.type==='내부장소');};
function evaluate(course,end,day,minute,budget){const nodes=[origin,...course,end],segments=[];let clock=minute,move=0;for(let i=0;i<nodes.length-1;i++){const segment=pairs.get(`${nodes[i].id}:${nodes[i+1].id}`);if(!segment)return{status:'missing_actual_route',course};segments.push(segment);move+=segment.totalMoveMin;if(i<course.length){clock+=segment.totalMoveMin;const place=course[i],leave=clock+place.recommendedStayMin;if(!available(place,day,clock,leave))return{status:'availability',course,failedPlaceId:place.id,segments,totalMoveMin:move};clock=leave;}}
const stay=course.reduce((sum,p)=>sum+p.recommendedStayMin,0),total=move+stay+buffer;return{status:total<=budget?'feasible':'budget',course,placeIds:course.map(p=>p.id),segments,totalMoveMin:move,totalStayMin:stay,totalMin:total};}
function measure(slot,day,now,minute,budget,arrivalType,end){const raw=[1,2,3].flatMap(size=>perm(candidates,size)),relationship=raw.filter(allowed),evaluated=relationship.map(course=>evaluate(course,end,day,minute,budget)),feasible=evaluated.filter(x=>x.status==='feasible'),bestBySet=new Map();for(const item of feasible){const set=item.placeIds.slice().sort().join('|');if(!bestBySet.has(set)||bestBySet.get(set).totalMin>item.totalMin)bestBySet.set(set,item);}const deduplicated=[...bestBySet.values()].sort((a,b)=>a.totalMin-b.totalMin||a.placeIds.join('|').localeCompare(b.placeIds.join('|'))),byStatus=Object.fromEntries([...evaluated.reduce((m,x)=>m.set(x.status,(m.get(x.status)??0)+1),new Map()).entries()]),bySize=Object.fromEntries([1,2,3].map(size=>[size,{raw:raw.filter(c=>c.length===size).length,relationship:relationship.filter(c=>c.length===size).length,evaluated:evaluated.filter(c=>c.course.length===size).length,feasible:feasible.filter(c=>c.course.length===size).length,deduplicated:deduplicated.filter(c=>c.course.length===size).length}]));return{scenarioId:`ROUTE-DIAGNOSTIC-NAMPO-500M-${slot}-${budget}-${arrivalType}`,measurementGrade:'route_verified_diagnostic_slice',coverageMatrixKey:{borough:'중구',dayType:day,now,budgetMin:budget,arrivalType},arrivalType,candidateScope:{type:'radius_meters',centerPlaceId:origin.id,radiusM:500,candidatePlaceIds:candidateIds,selection:'반경 안의 모든 structured representative; 동일 좌표·명시적 same siteGroup·내부장소만 제외; top-N 없음. 현행 제품의 실제 경로 주변 생활권 범위보다 좁은 진단 slice이므로 공급량 결론에는 사용 금지.'},origin:{id:origin.id,lat:origin.lat,lon:origin.lon,reason:'자갈치시장 관광·상권 진입점'},destination:{id:end.id,lat:end.lat,lon:end.lon,reason:arrivalType==='return_to_origin'?'출발지 복귀':'부산근현대역사관 본관 별도 약속 거점'},dayType:day,now,budgetMin:budget,arrivalBufferMin:buffer,rawCoursePermutationCount:raw.length,relationshipFilteredCourseCount:relationship.length,actualRouteEvaluatedCourseCount:evaluated.length,deduplicatedFeasibleCourseCount:deduplicated.length,representativeCourseCount:deduplicated.length?1:0,newRecommendationCount:Math.max(0,deduplicated.length-1),representativeCourse:deduplicated[0]??null,alternativeCourses:deduplicated.slice(1),courseSizeComparison:bySize,zeroReasonBreakdown:byStatus,fullCandidateScope:true};}
const scenarios=slots.flatMap(([slot,day,now,minute])=>budgets.flatMap(budget=>[measure(slot,day,now,minute,budget,'return_to_origin',origin),measure(slot,day,now,minute,budget,'separate_destination',destination)])),payload={meta:{generatedAt:new Date().toISOString(),purpose:'남포권 500m 진단 slice의 모든 적격 후보와 실제 TMAP 전 구간·구조화 운영시간을 사용한 route_verified_diagnostic_slice. 현행 제품의 실제 경로 주변 생활권 공급량 결론에는 사용 금지.'},summary:{scenarioCount:scenarios.length,candidateCount:candidates.length,pairSnapshotCount:pairFile.summary.ok,diagnosticZeroResultRate:scenarios.filter(s=>!s.representativeCourseCount).length/scenarios.length},scenarios};fs.writeFileSync(OUTPUT,`${JSON.stringify(payload,null,2)}\n`);
const rows=scenarios.map(s=>`| ${s.arrivalType} | ${s.candidateScope.candidatePlaceIds.join(', ')} | ${s.rawCoursePermutationCount} | ${s.relationshipFilteredCourseCount} | ${s.actualRouteEvaluatedCourseCount} | ${s.deduplicatedFeasibleCourseCount} | ${s.representativeCourseCount} | ${s.newRecommendationCount} |`).join('\n');const sizes=scenarios.map(s=>`- ${s.arrivalType}: ${JSON.stringify(s.courseSizeComparison)}`).join('\n');
fs.writeFileSync(REPORT,['# 남포권 500m 실제 경로 진단 slice','', '- 등급: **route_verified_diagnostic_slice**. 자갈치시장 500m 반경의 모든 구조화 대표 후보와 실제 TMAP 도보 스냅샷을 사용한다.', '- 현행 제품 후보 범위는 실제 경로 주변 생활권이므로, 이 좁은 반경의 공급량·0개율을 제품 공급량 결론이나 데이터 보강 우선순위에 사용하지 않는다.', `- 후보: ${candidateIds.join(', ')}`, `- 실제 장소쌍: ${pairFile.summary.ok}/${pairFile.summary.pairCount}`, '- 후보 top-N 절단 없음. 동일 좌표·명시적 동일 siteGroup·내부장소만 제외했고, 활동 유형은 제외 조건으로 사용하지 않았다.', '', '| 도착 형태 | 후보 ID | 원시 순열 | 관계 통과 | 실제 경로 평가 | 중복 제거 유효 | 대표 | 새 추천 |','| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |',rows,'','## 1·2·3곳 비교','',sizes,'',`상세 fixture: \`${OUTPUT}\``].join('\n')+'\n');console.log(`남포 500m 실제 경로 진단: ${scenarios.map(s=>`${s.arrivalType} ${s.deduplicatedFeasibleCourseCount}`).join(', ')}`);
