import test from 'node:test';
import assert from 'node:assert/strict';
import 'tsx/cjs';
import { screenRuntime } from './support/screenRuntime.mjs';
import { createRequire } from 'node:module';
const { recordTitle, profileDisplayChanges } = createRequire(import.meta.url)('../../src/ui/profileDisplayModel.ts');
const tick=async()=>{for(let n=0;n<80;n++)await Promise.resolve();};
test('login and signup retain only their own email and clear departing passwords/errors', async()=>{
  const listeners={};
  const runtime=screenRuntime({'./AuthContext':{useAuth:()=>({authKind:'guest',signIn:async()=>{},signUp:async()=>false})},'./CaptchaVerificationSheet':{CaptchaVerificationSheet:'Captcha'},'expo-modules-core':{uuid:{v4:()=> 'fixture'}}});
  const {LoginScreen}=runtime.load('src/ui/LoginScreen.tsx');
  const screen=runtime.mount(LoginScreen,{navigation:{goBack(){},addListener:(name,fn)=>{listeners[name]=fn;return()=>{};}},readDocuments:async()=>({status:'ok',documents:[]})});
  screen.press('login-submit'); screen.get('auth-form-error');
  screen.get('login-email').props.onChangeText('login@example.test'); screen.get('login-password').props.onChangeText('login-secret');
  screen.press('login-mode-signup');
  assert.equal(screen.nodes(n=>n.props.testID==='auth-form-error').length,0);
  assert.equal(screen.get('login-email').props.value,''); assert.equal(screen.get('login-password').props.value,'');
  screen.get('login-email').props.onChangeText('signup@example.test'); screen.get('login-password').props.onChangeText('signup-secret'); screen.get('signup-password-confirm').props.onChangeText('signup-secret');
  screen.press('login-mode-login'); assert.equal(screen.get('login-email').props.value,'login@example.test'); assert.equal(screen.get('login-password').props.value,'');
  screen.press('login-mode-signup'); assert.equal(screen.get('login-email').props.value,'signup@example.test'); assert.equal(screen.get('signup-password-confirm').props.value,'');
  screen.get('login-password').props.onChangeText('temporary'); listeners.blur(); screen.render(); listeners.focus(); assert.equal(screen.get('login-password').props.value,'');
  await tick(); screen.unmount();
});
test('nickname save publishes a refresh only after successful repository result, independent of consent', async(t)=>{
  let notices=0;
  const unsubscribe=profileDisplayChanges.subscribe(owner=>{assert.equal(owner,'A');notices++;});
  t.after(unsubscribe);
  const runtime=screenRuntime({'./profileDisplayModel':{profileDisplayChanges},'./personalizationComposition':{personalizationSession:{invalidate(){throw Error('nickname is not consent');}}},'./liveActivity/learningEvidenceComposition':{liveLearningEvidence:{}},'expo-modules-core':{uuid:{v4:()=> 'fixture'}}});
  const ports=async()=>({supabaseAccountIdentityResolver:{resolve:async()=>({status:'account',identity:{subject:'A'}})},supabaseAccountProfileRepository:{readAccountProfile:async()=>({status:'ok',profile:{nickname:null}}),updateAccountNickname:async()=>({status:'updated',profile:{nickname:'새이름'}})}});
  const {AccountPersonalizationPanel}=runtime.load('src/ui/AccountPersonalizationPanel.tsx');
  const screen=runtime.mount(AccountPersonalizationPanel,{subject:'A',profile:true,getPorts:ports});await tick();assert.equal(notices,0);
  const save=screen.get('profile-nickname-save');
  assert.equal(save.props.children.props.children,'저장');
  const saveStyle=Object.assign({},...([save.props.style].flat()));
  assert.equal(saveStyle.backgroundColor,'#0066ff');assert.equal(saveStyle.alignItems,'center');
  screen.get('profile-nickname').props.onChangeText('새이름');screen.press('profile-nickname-save');await tick();assert.equal(notices,1);assert.equal(screen.get('profile-nickname').props.value,'새이름');
  screen.unmount();unsubscribe();
});
test('record title validates nickname and discards prior owner responses, refreshes after save without consent', async()=>{
  for(const name of [null,'','   ','a\n', 'x'.repeat(21)]) assert.equal(recordTitle(name),'나의 자투리 기록');
  assert.equal(recordTitle('  테스트  '),'테스트님의 자투리 기록');
  assert.equal(recordTitle('가'.repeat(20)),`${'가'.repeat(20)}님의 자투리 기록`);
  let subject='A'; const pending=[];
  const ports=async()=>({supabaseAccountIdentityResolver:{resolve:async()=>({status:'account',identity:{subject}})},supabaseAccountProfileRepository:{readAccountProfile:()=>new Promise(resolve=>pending.push(resolve))}});
  const runtime=screenRuntime({'./profileDisplayModel':{recordTitle,profileDisplayChanges},'@react-navigation/native':{useFocusEffect:cb=>runtime.react.useEffect(cb,[cb])}});
  const {useRecordTitle}=runtime.load('src/ui/useRecordTitle.tsx');
  const screen=runtime.mount(()=>({type:'Text',props:{testID:'title',children:useRecordTitle(subject,ports)}}),{});
  await tick(); assert.equal(screen.get('title').props.children,'나의 자투리 기록');
  subject='B'; screen.render(); await tick();
  pending[0]({status:'ok',profile:{nickname:'old-owner'}}); await tick(); assert.equal(screen.get('title').props.children,'나의 자투리 기록');
  pending[1]({status:'ok',profile:{nickname:'새이름'}}); await tick(); assert.equal(screen.get('title').props.children,'새이름님의 자투리 기록');
  profileDisplayChanges.notify('B'); screen.render(); await tick(); pending[2]({status:'ok',profile:{nickname:'바뀐이름'}}); await tick(); assert.equal(screen.get('title').props.children,'바뀐이름님의 자투리 기록');
  profileDisplayChanges.notify('B'); screen.render(); await tick(); pending[3]({status:'unavailable'}); await tick(); assert.equal(screen.get('title').props.children,'나의 자투리 기록');
  subject=null; screen.render(); assert.equal(screen.get('title').props.children,'나의 자투리 기록'); screen.unmount();
});
test('management is a separate screen, preserves order, guards logout duplicate/failure and clears stack on owner change', async()=>{
  let subject='A',fail=true,calls=0,back=0,resets=0;
  const runtime=screenRuntime({'@expo/vector-icons':{Feather:'Feather'},'./AuthContext':{useAuth:()=>({authKind:subject?'account':'guest',accountSession:subject?{user:{id:subject}}:null,signOut:async()=>{calls++; if(fail)throw Error('private'); subject=null;}})},'./AccountPersonalizationPanel':{AccountPersonalizationPanel:'Nickname'},'./OwnedDeletionPanel':{OwnedDeletionPanel:'Delete'},'./mainTabNavigation':{resetToProfile:()=>resets++}});
  const {ProfileManagementScreen}=runtime.load('src/ui/ProfileManagementScreen.tsx');
  const navigation={goBack:()=>back++};
  const screen=runtime.mount(ProfileManagementScreen,{navigation});
  assert.equal(screen.get('profile-management-back').props.children.props.size,28);
  const logoutStyle=screen.get('profile-management-logout').props.style;
  assert.equal(logoutStyle.alignItems,'center'); assert.equal(logoutStyle.borderWidth,1);assert.equal(logoutStyle.backgroundColor,'#171719');
  assert.match(JSON.stringify(screen.render()),/닉네임 변경하기.*Nickname.*Delete.*로그아웃하기/s);
  assert.equal(screen.nodes(n=>n.type==='Delete')[0].props.account,true);
  screen.press('profile-management-back'); assert.equal(back,1);
  const logout=screen.get('profile-management-logout').props.onPress; const first=logout();logout();await first;
  assert.equal(calls,1);assert.equal(resets,0);assert.match(JSON.stringify(screen.render()),/로그아웃하지 못했어요/);assert.doesNotMatch(JSON.stringify(screen.render()),/private/);
  fail=false;await screen.press('profile-management-logout');screen.render();assert.equal(resets,1);assert.equal(screen.nodes(n=>n.type==='Nickname').length,0);screen.unmount();
  subject='A';const next=runtime.mount(ProfileManagementScreen,{navigation});subject='B';next.render();assert.equal(resets,2);assert.equal(next.nodes(n=>n.type==='Nickname').length,0);next.unmount();
});
